name: Feature Request
description: Request a feature!
title: "Category: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Please replace `Category` in the title with what this feature will be targeting, such as Gameplay Changes, YAML option or Gameplay Additions.
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to see?
